Fix error on missing license
Error was:

| License= {{ '{{' }}{{ license_status }}|{{ addon.libretro_info.license.split('|') | join(', ') | default('?') }}{{ '}}' }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'license'